Added unit test for display.set_icon()
pygame/pygame pull request #2049
Opened 2020-08-20 20:43 UTC by amipy

Added a unit test for pygame.display.set_icon()
This is my first time submitting one of these, let me know if something is wrong so I can try to do it better next time.

2020-08-24 07:35 UTC, MightyJosip commented
This unit test should be part of [this file](https://github.com/pygame/pygame/blob/1476009b05919c96b22ef9abeabc5a623c552ce7/test/display_test.py#L379-L400)

2020-08-30 09:48 UTC, illume requested changes
Looks good, just needs to be moved into the display_test.py file. 

(maybe the class could be renamed to TestSetIcon?)

2020-08-30 10:02 UTC, illume commented on test/set_icon_test.py
> +    def test_integer(self):
This test is needed.

2020-08-30 10:02 UTC, illume commented on test/set_icon_test.py
> +    def test_dict(self):
This test is needed.

2020-08-30 10:02 UTC, illume commented on test/set_icon_test.py
> +    def test_list(self):
This test is needed.

2020-08-30 10:02 UTC, illume commented on test/set_icon_test.py
> +    def test_audio_not_initialized(self):
This test is needed.

2020-08-30 10:02 UTC, illume commented on test/set_icon_test.py
> +    def test_display_not_initialized(self):
👍

2020-08-30 10:04 UTC, illume commented
There was already a PR open for testing display.set_icon... https://github.com/pygame/pygame/pull/2042
However, I think your test has some value still. The other test does not run by default in CI, only when running locally.

2020-09-09 05:49 UTC, illume commented
If you want to continue this, please feel free to comment here. Closing for now to keep our list of PRs clean.

2020-09-09 05:49 UTC, closed without merging