First pass at backwards compatible pygame alpha blit
pygame/pygame pull request #2213
Opened 2020-10-19 17:27 UTC by MyreMylar

Got the test to pass at least.

2020-10-20 11:20 UTC, MyreMylar commented
Some speed tests:

new-default SDL1-style alpha-blit (using SSE2):

```
         256002 function calls in 1.854 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.166    0.166    1.854    1.854 pygame_blit_sdl1_speed_test.py:9(speed_test_blits)
   128000    1.055    0.000    1.055    0.000 {method 'fill' of 'pygame.Surface' objects}
    64000    0.610    0.000    0.610    0.000 {method 'blit' of 'pygame.Surface' objects}
    64000    0.023    0.000    0.023    0.000 {method 'get_at' of 'pygame.Surface' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

old-default SDL2 style blit (uses some form of intrinsics in SDL2):

```
         256002 function calls in 1.832 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.185    0.185    1.832    1.832 pygame_blit_sdl2_speed_test.py:10(speed_test_blits)
   128000    1.054    0.000    1.054    0.000 {method 'fill' of 'pygame.Surface' objects}
    64000    0.568    0.000    0.568    0.000 {method 'blit' of 'pygame.Surface' objects}
    64000    0.025    0.000    0.025    0.000 {method 'get_at' of 'pygame.Surface' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

new-default SDL1 style alpha-blit (without any SSE2/NEON intrinsics)
```
         256002 function calls in 6.070 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.172    0.172    6.070    6.070 pygame_blit_sdl1_speed_test.py:9(speed_test_blits)
    64000    4.836    0.000    4.836    0.000 {method 'blit' of 'pygame.Surface' objects}
   128000    1.038    0.000    1.038    0.000 {method 'fill' of 'pygame.Surface' objects}
    64000    0.024    0.000    0.024    0.000 {method 'get_at' of 'pygame.Surface' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

So the new SDL1 blitter is fairly comparable, though slightly slower, than the default SDL2 one and both of them are a lot faster than not using intrinsics. 

It's possible we could improve the speed a bit without affecting the accuracy, I'm not an SSE2 intrinsics expert.

2020-10-20 11:21 UTC, MyreMylar commented
Was using this to do speed testing (changing the flag to switch to the SDL2 blitter):

```
from sys import stdout
from pstats import Stats
from cProfile import Profile

import pygame
pygame.init()


def speed_test_blits():

    nums = [0, 1, 65, 126, 127, 199, 254, 255]
    results = {}
    for iterations in range(0, 1000):
        for dst_r, dst_b, dst_a in zip(nums, reversed(nums), reversed(nums)):
            for src_r, src_b, src_a in zip(nums, reversed(nums), nums):
                src_surf = pygame.Surface((66, 66), pygame.SRCALPHA, 32)
                src_surf.fill((src_r, 255, src_b, src_a))
                dest_surf = pygame.Surface((66, 66), pygame.SRCALPHA, 32)
                dest_surf.fill((dst_r, 255, dst_b, dst_a))

                dest_surf.blit(src_surf, (0, 0))
                key = ((dst_r, dst_b, dst_a), (src_r, src_b, src_a))
                results[key] = dest_surf.get_at((65, 33))


if __name__ == '__main__':
    profiler = Profile()
    profiler.runcall(speed_test_blits)
    stats = Stats(profiler, stream=stdout)
    stats.strip_dirs()
    stats.sort_stats('cumulative')
    stats.print_stats()
```

2020-10-21 15:45 UTC, MyreMylar commented
Checked over the test cases in the original report (#1289) and they all look/print like they do in SDL1 now. So that's nice.

2020-10-21 17:11 UTC, MyreMylar commented
With this PR you should now be able to do:

```
import os
import pygame
os.environ['PYGAME_BLEND_ALPHA_SDL2'] = '1'

pygame.init()
```

To set the blitter back to how it worked before this PR.

2020-10-21 18:57 UTC, MyreMylar commented
Ok, that is probably enough fiddling. To summarise:

- This adds a new default blitter for surfaces with alpha. The default blitter prioritises accuracy to what SDL1 did over speed.
- There are SSE2 optimised versions of the blitter that cover three common cases:
    - Two surfaces with per-pixel alpha and no surface alpha.
    - A source surface with per pixel alpha _and_ surface alpha, blitted to a destination surface with regular pixel alpha.
    - A source surface with per-pixel alpha blitted to an opaque surface.
- There is a regular non-intrinsic alpha blitter (that has been in pygame for ages) that is used for any cases directed to the alpha blitter outside of the three above.
- The blitter doesn't handle colorkey alpha, that is passed over to SDL2 as before.
- The blitter doesn't handle blits with RLE encoded surface, they are is also passed over to SDL2.
- You can switch from this new default blitter to SDL2 by passing the flag `BLEND_ALPHA_SDL2` when blitting, or by setting the environment variable `PYGAME_BLEND_ALPHA_SDL2` before calling `pygame.init()`.

This should resolve all the cases raised in #1289 and maybe will help with some others in the tracker, I haven't checked through carefully yet.

2020-10-21 19:09 UTC, MyreMylar commented
Speed wise, in my tests (rough code posted above):

 - slightly slower than SD2 blitter when doing pixel alpha surface to pixel alpha surface.
 - equivalent or slightly faster when blitting with a surface with pixel alpha & surface alpha (from set_alpha()) or to an opaque surface.

I don't have any particular ideas for improving that right now.

2020-10-22 06:41 UTC, illume commented
Nice work :) This also fixes the issue in https://github.com/pygame/pygame/issues/742 

This example used to error with:
> pygame.error: Blit combination not supported

```python
import pygame as pg
pg.init()
surf = pg.display.set_mode((320,240))
font = pg.font.SysFont("Arial", 24)
image = font.render("Test", 0, (255,255,255), (0,0,0))
print(image.get_colorkey()) #returns None in both SDL1/SDL2.
image.set_alpha(255)
surf.blit(image,(0,0))
```

But now it doesn't.

2020-10-22 11:46 UTC, MyreMylar commented
Looks like the arm CI build doesn't use the SSE2 optimised path at all, so the test issue was likely coming from a lack of support for surface_alpha() in the non-sse2 version of the alpha blend which I've now changed.

2020-10-22 14:05 UTC, illume approved these changes
```
_/=====\_
| great! |
---------\
          `_  
             🦜 
```

2020-10-22 16:08 UTC, MyreMylar commented
Hopefully this doesn't cause chaos in everyone's apps, but I'm bracing for it just in case.

2020-10-22 16:48 UTC, illume commented
The unit tests pass locally on Mac.

I see there's a difference in solarwolf:

<img width="800" alt="Screenshot 2020-10-22 at 18 44 26" src="https://user-images.githubusercontent.com/9541/96904122-f7cd2a00-1496-11eb-9d1d-e1922314c635.png">

In the screen where you can load a save game.

2020-10-22 16:48 UTC, illume requested changes
There's something weird going on with solarwolf.

2020-10-23 11:26 UTC, MyreMylar commented
This is my current solarwolf related issue with this PR on windows:

```
import pygame

pygame.init()


def textshadowed(color, text, center=None, pos='center'):
    font = pygame.font.Font(None, 32)
    darkcolor = [int(c // 2) for c in color]
    if text is None: text = ' '
    try:
        img1 = img2 = font.render(text, 1, color)
        img2 = font.render(text, 1, darkcolor)
    except (pygame.error, TypeError):
        img1 = img2 = pygame.Surface((10, 10))

    newsize = img1.get_width() + 2, img1.get_height() + 2
    img = pygame.Surface(newsize)

    print("start:")
    print("img.get_flags():", img.get_flags())
    print("img.get_at((0, 0)):", img.get_at((0, 0)))
    print("img.get_colorkey():", img.get_colorkey())
    print("img.get_shifts():", img.get_shifts())
    print("img.get_masks():", img.get_masks())
    print("img.get_bitsize():", img.get_bitsize())
    print("img.get_bitsize():", img.get_bytesize())

    img.blit(img1, (0, 0))
    img = img.convert()

    print("\nafter blit:")
    print("img.get_flags():", img.get_flags())
    print("img.get_at((0, 0)):", img.get_at((0, 0)))
    print("img.get_colorkey():", img.get_colorkey())
    print("img.get_shifts():", img.get_shifts())
    print("img.get_masks():", img.get_masks())
    print("img.get_bitsize():", img.get_bitsize())
    print("img.get_bitsize():", img.get_bytesize())

    img.set_colorkey((0, 0, 0), pygame.RLEACCEL)

    print("\npost set_colorkey:")
    print("img.get_flags():", img.get_flags())
    print("img.get_at((0, 0)):", img.get_at((0, 0)))
    print("img.get_colorkey():", img.get_colorkey())
    print("img.get_shifts():", img.get_shifts())
    print("img.get_masks():", img.get_masks())
    print("img.get_bitsize():", img.get_bitsize())
    print("img.get_bitsize():", img.get_bytesize())

    return img


screen = pygame.display.set_mode((320, 240))
screen.fill((255,255,255))

text_render = textshadowed((160, 200, 250), 'A', (190, 170), "midright")
screen.blit(text_render, (50, 50))

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    pygame.display.update()

```

Output pre-PR:
![image](https://user-images.githubusercontent.com/13382426/96998188-ef263380-152a-11eb-8cdf-80a5ed51402c.png)

Output post-PR:
![image](https://user-images.githubusercontent.com/13382426/96998143-e0d81780-152a-11eb-9765-d4bca7b127bf.png)

So far I can't figure out why the colorkey isn't working after using the new blitter before it is set.

2020-10-23 12:42 UTC, illume commented
With the current commit it looks like your "Output pre-PR" one to me:
<img width="66" alt="Screenshot 2020-10-23 at 14 41 37" src="https://user-images.githubusercontent.com/9541/97004821-e3903800-153d-11eb-9ae7-6606cb851403.png">

2020-10-23 17:26 UTC, merged