WIP: rearrange event posting, zero-init event struct
pygame/pygame pull request #2250
Opened 2020-10-26 13:23 UTC by robertpfeiffer

2020-11-07 07:39 UTC, illume commented
Hi,

is this ready to be reviewed, or is there work ongoing?
How should I test this PR?

#1238 is still open because of the unicode field is not being filled.

2020-11-07 07:53 UTC, ankith26 commented
I have plans to do a major refactor for event stuff. I have identified a lot of issues that my refactor can potentially fix (including the unicode issue, which looks like it’s out of this PRs scope). 
However, this PR does some nice code cleanup and updates, which can be a good base for my work

2020-11-08 15:58 UTC, robertpfeiffer commented
This can be merged if @ankith26 sees no problems with it.

2020-11-08 17:58 UTC, ankith26 commented
Like I have said in the above message, this PR makes some good changes, and can make a great base for my work.

2020-11-08 18:37 UTC, illume requested changes
Can you please add a PR description?

It seems like it's refactoring and cleaning up, but not fixing anything. Does this fix anything that I can reproduce? Is the commit message saying it fixes the issue correct? If it doesn't fix that issue, can you please rebase this and fix the commit message(s)?

I think it's best if we merge this into a separate branch (perhaps called `event-refactor`). It feels too risky to merge at the moment.

I could squash-merge this myself, and try to write a better commit and create the branch. However, I'm not sure I understand the reasons for all the changes. I'll wait for @robertpfeiffer to do a rebase, or instruction for me to go ahead with moving it into a `event-refactor` branch.

2020-11-09 04:07 UTC, ankith26 commented
Here are some things in this PR that are quite helpful
https://github.com/robertpfeiffer/pygame/blob/ca0ce79d589490d403ed0eb998ca7a56adced2ef/src_c/event.c#L124

https://github.com/robertpfeiffer/pygame/blob/ca0ce79d589490d403ed0eb998ca7a56adced2ef/src_c/event.c#L318

https://github.com/robertpfeiffer/pygame/blob/ca0ce79d589490d403ed0eb998ca7a56adced2ef/src_c/event.c#L1285

TBH, my upcoming PR removes the other changes made in this PR. If @robertpfeiffer has no problem with this, I can make these changes in my PR, without having to merge this (I hope you understand, im just suggesting this because it makes it easier for me)

2020-11-13 09:58 UTC, illume commented
Thanks for the great description @robertpfeiffer !

2020-11-14 03:08 UTC, ankith26 commented
This PR is going to have a lot of merge conflicts with my (upcoming) PR. 
Like I have said before, I am anyways going to have to remove some of the code, that this PR introduces (the part where we explicitly handle KEYDOWN events)

So what is the course of action?? Here are some things we can do
1) merge this PR, and then my PR can deal with the merge conflicts
2) I can make a PR and then @robertpfeiffer can also commit to that PR to make any other necessary changes that needs to be done

2020-11-14 05:43 UTC, ankith26 commented
> * At the very least, more comments will dissuade the next poor soul from trying to refactor this code without understanding what is going on.

Hah, well I can understand :) it took a while for me to understand what is going on with event.c, but now I can tell that I understand it fairly well. I have written a lot of comments for the new stuff I have included too, so that future contributors do not get totally confused

2020-11-18 12:47 UTC, robertpfeiffer commented
I undid the init change to get at least the *obvious* bug fixes this merged.

2020-12-07 16:23 UTC, robertpfeiffer commented
What's the plan here? I'd like to work on the other blockers for touch/android, as long as this isn't resolved, I can't.

2020-12-08 04:07 UTC, ankith26 commented
The PR I made address all the issues this PR address, so, unless my PR is missing anything that this PR addresses, I think we might have to potentially close this PR. Hope you don’t mind :) 

Meanwhile, if you have a bit of time to spare, I would appreciate it a lot if you could review my PR, since you have much more experience with event stuff than me :)

2020-12-21 17:06 UTC, illume commented
This was continued and superseded in the other event refactor PRs.

2020-12-21 17:06 UTC, closed without merging