Add color.update and rect.update
pygame/pygame pull request #2277
Opened 2020-10-30 15:22 UTC by zoldalma999

#1049 

- [x] C code for rect.update()
- [x] Tests for rect.update()
- [ ] Docs for rect.update()
- [ ] C code for color.update()
- [ ] Tests for color.update()
- [ ] Docs for color.update()

2020-10-31 11:16 UTC, ankith26 requested changes

2020-10-31 11:16 UTC, ankith26 commented on src_c/color.c
> +            PyErr_SetString(PyExc_ValueError, "invalid color argument");
Nice work on the PR :) 👍 
A small nitpick, you can use a macro to set error and return NULL, just like.
`return RAISE(PyExc_ValueError, "invalid color argument");`

2020-11-02 11:23 UTC, ankith26 approved these changes

2020-11-02 11:24 UTC, ankith26 commented
Nice work on the PR, the new methods will be really useful :) 👍

2020-11-02 11:28 UTC, ankith26 commented
Close and open to run the CI again :)

2020-11-02 13:12 UTC, MightyJosip requested changes
Can you also modify the files connected to the type hints: (https://github.com/pygame/pygame/blob/main/buildconfig/pygame-stubs/color.pyi and https://github.com/pygame/pygame/blob/main/buildconfig/pygame-stubs/rect.pyi)

2020-11-02 16:14 UTC, MightyJosip approved these changes
Thanks

2020-11-04 21:42 UTC, nthykier commented
For reference, I would prefer if Colors are immutable.  See https://github.com/pygame/pygame/issues/1049#issuecomment-721990272 for my rationale.

2020-11-07 07:33 UTC, illume commented
I'd like to leave this open until we reach some sort of consensus on immutability with Color.

2020-11-07 11:11 UTC, illume approved these changes
👍 very nice, thank you.

Just waiting for more discussion on the Color immutable thing before merging.

2020-11-08 02:19 UTC, ankith26 commented
I totally support the idea of mutable colours and this PR looks very good to me, considering the fact that colours are already mutable (you can set the r, g, b and a attribute of the Color object)

2020-11-08 18:06 UTC, illume commented
Good point @ankith26.

2020-11-08 18:07 UTC, merged