checking pip version
pygame/pygame pull request #2705
Opened 2021-08-30 20:55 UTC by anukaal

2021-08-31 09:42 UTC, robertpfeiffer requested changes

2021-08-31 09:42 UTC, robertpfeiffer commented on setup.py
> +if sys.version_info < (3, 6):
why is this here, and not with the other version checks?

2021-08-31 09:42 UTC, robertpfeiffer commented on setup.py
> +         pip_version = tuple([int(x) for x in pip.__version__.split('.')[:3]])
why is pip supposed to be a dependency when building a wheel?

2021-09-17 23:32 UTC, Starbuck5 commented
I think I'm going to close this PR.

From reading the comments on another repository you added this exact PR to, I learned that this is so users on older versions of pip don't get confused if it attempts to install a version that isn't compatible with their python. Since the python_requires tag isn't supported on older pip: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires.

However, we don't need this patch, because we still support older Pythons, like 2.7 and 3.5.

2021-09-17 23:32 UTC, closed without merging