Remove Py2 and SDL1 C code
pygame/pygame pull request #2812
Opened 2021-11-01 00:24 UTC by Starbuck5

Ran the codebase through a script to remove `#if`s for SDL1/SDL2, and PY2/PY3.

I also edited the README, setup.py, and CI to reflect this.

I did not take any action on 3.5 but that will probably be dropped for 2.1 as well.

2021-11-01 06:12 UTC, ankith26 approved these changes
Real nice PR! This is a great start on 2.1 👍 🎉 
Let's do these changes incrementally in multiple PRs, and we should merge this one ASAP so that more work can happen on this :)

2021-11-01 08:48 UTC, ankith26 requested changes

2021-11-01 08:48 UTC, ankith26 commented on src_c/base.c
> +#if !defined(PYPY_VERSION)
This whole block should be removed, right?

2021-11-07 02:53 UTC, Starbuck5 commented
The contents of this PR have been split up into several other better PRs, closing.

2021-11-07 02:53 UTC, closed without merging