Fix drawing of big ellipses
pygame/pygame pull request #2880
Opened 2021-12-03 15:01 UTC by MightyJosip

This fixes #2879
Before this patch with big enough value calculation can exceed the int max value on the line 1912 and 1914 (same can be said about the function that draws ellipse with line width)
https://github.com/pygame/pygame/blob/40991f75e8b8c14a91acf43d4b16788c409abbf4/src_c/draw.c#L1912-L1914
And because of that you can end up with that weird shape (won't get into much details about why exactly do you get "rotated square")
Edge value was if the width was 1024 and height was 1024; or anything that gives you the bigger value of (width^2)*height (because that is 2^31, and int supports up to 2^31 - 1)

2021-12-03 16:53 UTC, ankith26 approved these changes
LGTM, nice PR! 🥳 👍 
Not something that should block this PR from being merged, but maybe a unit test for drawing large ellipses might be a good idea?

2021-12-11 09:57 UTC, MyreMylar commented
Before PR:

![image](https://user-images.githubusercontent.com/13382426/145672023-c10c4434-163e-4ab5-9587-b6b0dbf922a4.png)


After PR:

![image](https://user-images.githubusercontent.com/13382426/145672039-29deecf5-a644-4cbb-8d40-fabfca1885f0.png)


Test code used:

```
import pygame

pygame.init()


screen = pygame.display.set_mode((1920, 1080))

pygame.draw.ellipse(screen, pygame.Color('#FF0000'), pygame.Rect((0, 0), (2048, 2048)), 2)
clock = pygame.time.Clock()
running = True

while running:

    clock.tick(60)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            running = False

    pygame.display.update()

```

LGTM 👍 


I think adding a test case is a good idea. I would suggest adding one large size to `test_ellipse` here:

https://github.com/pygame/pygame/blob/c15cc0dd8b4e8b808e658ec89adb02d105e14697/test/draw_test.py#L502

Then adding an additional test after this:

https://github.com/pygame/pygame/blob/c15cc0dd8b4e8b808e658ec89adb02d105e14697/test/draw_test.py#L512-L514

if the `border_width = 1` that instead checks four points, inwards 2 pixels and rotated 45 degrees inside the ellipse are *not* the ellipse colour. 

I'm not sure of the maths of how to calculate those points though... maybe this could help:

https://math.stackexchange.com/questions/3200370/rotate-a-point-on-an-ellipse-by-an-angle-and-calculate-the-distance-between-them

Orrrr you could bodge it a little because with the current test values of 4 & 5 and the proposed new one of `(2048, 2048)` the ellipse is basically a circle which makes it a lot easier to calculate?

2021-12-11 10:00 UTC, MyreMylar requested changes
Changing to request changes to ask for a test please :)

2021-12-11 16:04 UTC, MyreMylar approved these changes
LGTM 👍

2021-12-11 16:04 UTC, merged