Fix rect drawing with width
pygame/pygame pull request #2881
Opened 2021-12-03 17:32 UTC by MightyJosip

Not much explanation needed, this is a fix for #2862

2021-12-11 03:51 UTC, ankith26 commented
whoops, seems like the manylinux1 builds are not happy. Might have to do something with the fact that `centos5` uses an old gcc

2021-12-11 21:14 UTC, MyreMylar approved these changes
Tested it locally and it does what it says on the tin.

Looks good. I like the new, properly rectangular, corners.

2021-12-16 00:18 UTC, illume requested changes
Thanks. Lgtm too.

A test case would be nice if possible. If you don’t have time, let me know… I can whip one up?

2021-12-18 07:52 UTC, ankith26 reviewed
Whoops looks like a merge conflict fix went bad here 😅 
Left some reviews that should be fixed
Also once your PR is done you should do a `python3 setup.py format` to fix lint

2021-12-18 07:52 UTC, ankith26 commented on src_c/draw.c
> +        color = (Uint32)PyInt_AsLong(colorobj);                            \
This change breaks stuff, because the `PyInt_*` macros no longer exist

2021-12-18 07:52 UTC, ankith26 commented on src_c/draw.c
> +    GAME_Rect *rect = NULL, temp;
use `SDL_Rect` in place of `GAME_Rect`

2021-12-18 07:52 UTC, ankith26 commented on src_c/draw.c
> +        MODINIT_ERROR;
do `return NULL;` instead of `MODINIT_ERROR;`

2021-12-18 16:18 UTC, MightyJosip commented
Closing because this branch is in a weird state after rebasing, continued in #2927

2021-12-18 16:18 UTC, closed without merging