"SDL_CreateWindowFrom" in "display" module
pygame/pygame pull request #2981
Opened 2022-01-09 12:08 UTC by Rabbid76

the environment variable "SDL_WINDOWID" is set, use "SDL_CreateWindowFrom" to create the window in "display.set_mode"

[Using 'SDL_WINDOWID' does not embed pygame display correctly into another application #1574](https://github.com/pygame/pygame/issues/1574)

2022-01-10 05:41 UTC, ankith26 reviewed
Thanks for the PR! 🎉 
I can't really provide an in-depth review because I'm not too experienced around display.c myself, but at a glance I noticed
1) `atoll` can return 0 when no conversion happens. IG in that case, `SDL_CreateWindow` should be called
2) [SDL_CreateWindowFrom](https://wiki.libsdl.org/SDL_CreateWindowFrom) docs mention 
> In some cases (e.g. OpenGL) and on some platforms (e.g. Microsoft Windows) the hint SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT needs to be configured before using SDL_CreateWindowFrom().

So I wonder how we should be handling this

2022-01-16 18:54 UTC, illume requested changes
Thank you very much. This is an important backwards compatibility fix.

Ankith already mentioned that atol can return an error.

Additionally, I wanted to ask about 32bit and 64bit windows... Is atol (long long?) the correct call to make on both 32/64 bit architectures?

2022-01-16 18:56 UTC, illume commented
I see there is test code here: https://github.com/pygame/pygame/issues/1574#issuecomment-1003910013
It would be good to confirm that the test code works on 32bit python and 64bit python.

2022-01-16 20:21 UTC, Rabbid76 commented
The return type of [`std::atoll`](https://en.cppreference.com/w/cpp/string/byte/atoi) is `long long`. An alternative solution might be [`std::stoll`](https://en.cppreference.com/w/cpp/string/basic_string/stol).

2022-03-12 11:40 UTC, ankith26 commented
Revisiting this PR, I believe [`atol`](https://www.tutorialspoint.com/c_standard_library/c_function_atol.htm) is the right function to use here. It returns a `long` not a `long long`, which should be the better datatype to use here IG. Because the size of a void pointer is not fixed at 8 bytes like `long long`, instead it can vary by implementation. I believe the sizeof `long` best matches the size of a void pointer on most platforms and configurations.

As mentioned above, like `atoll`, this function can return `0` on fail too. The error handling bit can look something like
```c
if (!window_handle) {
    /* NULL window_handle can segfault when *window_handle executes */
    window_handle = "";
}

long window_id = atol(window_handle);
if (!window_id && *window_handle != '0') {
    /* window_id is 0 when atol errors. It can also be 0 when the input was 0 */
    return RAISE(pgExc_SDLError, "'SDL_WINDOWID' must be an integer");
}
```

As illume pointed above, it would be good to test this change on 32 bit and 64 bit windows, bonus points if this can be put in a unit test ;)

2022-07-13 15:37 UTC, MyreMylar commented
@Rabbid76 are you still interested in finishing this off? It has been a while, so we could find someone else to take this over to get it into 2.1.3.

2023-02-19 00:29 UTC, illume approved these changes
👍 Thanks

2023-02-19 00:29 UTC, merged