Added Vector subclassing
pygame/pygame pull request #3088
Opened 2022-03-21 07:03 UTC by novialriptide

Fix: https://github.com/pygame/pygame/issues/2996

2022-03-21 15:14 UTC, ankith26 requested changes
Needs some unit tests too

2022-03-21 15:14 UTC, ankith26 commented on src_c/math.c
> +    Py_ssize_t i;
what is this for here? Can be removed

2022-03-21 15:14 UTC, ankith26 commented on src_c/math.c
> -        }
why was this check removed? It is very much needed, so it needs to be added back

2022-03-21 15:14 UTC, ankith26 commented on src_c/math.c
> +    ret = (pgVector *)_vector_subtype_new(Py_TYPE(self), self->dim);
minor code appearance nitpick, this bit of code will look neater if it's expressed in one line, like 
` pgVector *ret  = (pgVector *)_vector_subtype_new(Py_TYPE(self), self->dim);`
Here, and also in all functions below

2022-03-21 15:14 UTC, ankith26 commented on src_c/math.c
> +
```suggestion
    if (!ret) {
        return NULL;
    }
```
Not really a bug introduced by this PR but can be fixed here, this is missing error forwarding return

2022-03-21 15:14 UTC, ankith26 commented on src_c/math.c
> +    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE, /* tp_flags */
You put this flag for the `pgVectorIter_Type` which is not needed IMHO. I don't think users want to subclass something that is not even documented pygame API, probably out of scope for this PR

2022-03-24 09:16 UTC, Starbuck5 commented
This is starting to look really clean! As Ankith mentioned, it needs tests. It could also probably use a note in the docs.

2022-03-25 03:46 UTC, ankith26 commented on docs/reST/ref/math.rst
> +      will recognize this and return instances of the subclass.
vectors were always subclassable. What this PR changes is the return types of inherited methods to match the subclass

2022-03-25 03:46 UTC, ankith26 commented on src_c/math.c
> +    if (vec) {
This makes sense, pretty sure `tp_new` sets a python error and returns `NULL`, afterall it's just another python function.

2022-03-27 13:05 UTC, ankith26 approved these changes
LGTM! Thanks for the PR 👍 🎉

2022-03-27 23:13 UTC, Starbuck5 commented
You got the explicit methods, but it still fails on math.

```
>>> class VEC(pygame.Vector2):
...     pass
...
>>> a = VEC(5,6)
>>> b = VEC(7,8)
>>> a + b
<Vector2(12, 14)>
>>> type(a + b)
<class 'pygame.math.Vector2'>
```

It passes `-a` though. You should also add a test for that.

2022-03-27 23:19 UTC, Starbuck5 commented on src_c/math.c
>          Py_ssize_t i;
This isn't your fault, but I noticed almost all the rest check if the value is NULL and return NULL there. You could change this method to be consistent with that.

2022-04-03 15:24 UTC, MyreMylar requested changes
This resolves the original issue mentioned however I noticed some inconsistency in whether we now return a VectorN or whether we return a subtype.

For example:

```
c = MyVector(5,10)
d = c.copy()
type(d)
<class '__main__.MyVector'>
e = c + d
type(e)
<class 'pygame.math.Vector2'>
```

Why does adding two MyVector objects produce a Vector2? Is this what we want to happen or should it also return an instance of the subtype? There are still a handful of places (including these basic math ops) where we are returning an instance of the parent class rather than the subclass and I think we should definitely have a solid think about each one.

Apologies if this has already been done somewhere, but I couldn't see it in the PR comment thread.

2022-04-05 01:36 UTC, novialriptide commented
> Apologies if this has already been done somewhere, but I couldn't see it in the PR comment thread.

Yup, Starbuck5 has mentioned this issue. I'm currently working on a solution to that. 

> is this what we want to happen or should it also return an instance of the subtype?

Nope, this isn't what is supposed to happen.

2022-04-05 16:20 UTC, ankith26 reviewed
In addition to the generic math function not being fixed that is already mentioned before, I noticed that vector swizzling also returns a pygame vector instance... which should probably be fixed too...
```
>>> class MyVec(pygame.Vector2): pass
... 
>>> MyVec(2, 3).xx 
<Vector2(2, 2)>
```
And there are some elementwiseproxy functions too that seem to deal with vectors directly

2022-04-08 07:39 UTC, novialriptide commented
There are a few more that needs to support subtype, but I'm pushing my latest changes to show some progress.

2022-04-20 13:57 UTC, novialriptide commented
There's a little bit of an oopsie with the subclassing PR, so for swizzling, let's say you have this piece of code
```python
class MyVector2(pygame.Vector2):
  pass

print(MyVector2(3, 5).xy)
```
This piece of code will work just fine, assuming it'll return a `MyVector2` type instead of a `pygame.Vector2`, but what if we add this at the end?
```python
print(MyVector2(3, 5).xyx
```
This will return a `pygame.Vector3` type instead of a `MyVector2` since it has 3 dimensions instead of 2.

Any ideas on this problem? Should we disable swizzling if the Vector class has been subclassed, only return `pygame.VectorN` for sizzling, or keep it how I described it, return `pygame.VectorN` if it can't return itself.

2022-04-21 06:01 UTC, ankith26 reviewed
Since I see this function call pattern `(pgVector *)_vector_subtype_new(Py_TYPE(var), var->dim);` is almost universal in this file, I'd suggest implementing the function signature like 
`pgVector *_vector_subtype_new(pgVector *base);` 
so that the call simplifies to `_vector_subtype_new(var);`

2022-04-22 05:48 UTC, ankith26 requested changes
Also needs typehint changes in addition to some extra reviews I left

2022-04-22 05:48 UTC, ankith26 commented on src_c/math.c
> +static PyObject *
Return type here could be `pgVector *` because almost all function calls to this cast this to `pgVector *`

2022-04-22 05:48 UTC, ankith26 commented on test/math_test.py
> +
extend this with tests for subclass math operations and elementwise tests too

2022-04-22 05:48 UTC, ankith26 commented on test/math_test.py
> +
same as above review

2022-04-22 05:48 UTC, ankith26 commented on src_c/math.c
> +        vec = ((vector_elementwiseproxy *)baseObj)->vec;
```suggestion
        vec = ((vector_elementwiseproxy *)baseObj)->vec;
        dim = vec->dim;
        tmp = vec->coords;
```
For better code clarity

2022-04-22 05:48 UTC, ankith26 commented on src_c/math.c
> +        vec = ((vector_elementwiseproxy *)expoObj)->vec;
```suggestion
        vec = ((vector_elementwiseproxy *)expoObj)->vec;
        dim = vec->dim;
        tmp = vec->coords;
```

2022-04-22 08:26 UTC, Starbuck5 approved these changes
Thanks for sticking through this Novial! This is cool. 🎉

The type test might want a test that the swizzle type is unrelated to the subtype, since we've decided to do it that way.

Ankith says something about needing type hints, I'm not sure how that would work at all. Typing makes my brain hurt.

2022-04-23 02:49 UTC, ankith26 commented on src_c/math.c
> +            return PyErr_NoMemory();
```suggestion
            return (pgVector *)PyErr_NoMemory();
```

2022-04-23 03:56 UTC, ankith26 approved these changes
LGTM! Thanks for the PR 👍 🎉 

(I mentioned that typestubs need fixes after this PR, but as discussed on discord I will be opening a new PR for that)

2022-04-23 04:05 UTC, ankith26 commented
For those OOTL, we discussed swizzling return types on discord, and the current decision is to keep old behaviour for swizzling, returning `VectorN` instances even when vector subclasses are swizzled.

This PR is bit of an API change, but it's a step in the right direction. User code that subclasses vectors should not break if those subclasses were designed with Liskov substitution principle in mind

2022-04-23 04:08 UTC, merged