fix name/definition conflict for pgSurface_New
pygame/pygame pull request #3106
Opened 2022-03-31 13:35 UTC by pmp-p

There's a name conflict between https://github.com/pygame/pygame/blob/a1725cf7375f50a1719c09c758096617b2f4dc07/src_c/include/_pygame.h#L295 and  https://github.com/pygame/pygame/blob/a1725cf7375f50a1719c09c758096617b2f4dc07/src_c/surface.c#L107   

i suggest `pgSurface_New2` for the latter instead  because `pgSurface_New` already mentionned in C-API docs with a single argument.

that conflict appears when turning of C-API and trying to build static for https://github.com/pygame/pygame/issues/718

2022-03-31 19:51 UTC, novialriptide commented
> @novialriptide pgSurface_New2() is the historic _pygame.h helper https://github.com/pygame/pygame/blob/a1725cf7375f50a1719c09c758096617b2f4dc07/src_c/include/_pygame.h#L275
> 
> Using the same name just make the symbol reachable directly without pointer cast - and any code addition - when C-api is turned off.

Ah okay, my bad.

2022-04-01 16:44 UTC, MyreMylar approved these changes
This seems to compile fine and the surfaces tests and a relatively complex application all run. I sort of hate the name `pgSurface_New2` but that was in there already.

2022-04-05 16:01 UTC, ankith26 requested changes
I think there are many more places where such kind of conflict can arise, it's a common theme in the pygame C API. Why is only this one being fixed? Does this fix help with WASM? Because I think this conflict shouldn't be a problem otherwise

2022-04-05 16:07 UTC, ankith26 approved these changes
Thanks for the PR 👍 
I think in the long term this might need some more improvements, because ATM it's easy to confuse this as I got confusing while reviewing, then it took me more digging around the code to figure out what was going on

2022-04-05 16:09 UTC, merged