examples/mask.py remove red background
pygame/pygame pull request #3111
Opened 2022-04-01 19:45 UTC by brccabral

chimp image has a red background. When calculating collisions, the red background is determining the collision, removing the red background from the chimp image the collisions happen only between chimps, not between backgrounds.

2022-04-02 08:56 UTC, MyreMylar requested changes
this will only work for the current default chimp.png, not any other images supplied by a user to the example.

I think a better way to fix it right now is to swap the default image to one of the other example images that has an alpha channel rather than a colour key.

You can do this on line 207, changing it to:

```
imagename = os.path.join(main_dir, "data", "alien1.png")
```

2022-04-02 22:51 UTC, brccabral commented
Done, changed to alien1.png

2022-04-03 11:42 UTC, MyreMylar approved these changes

2022-04-04 03:40 UTC, ankith26 approved these changes
Thanks for the PR! 👍 🎉

2022-04-04 03:41 UTC, merged