Fix drawing of circles there intersect -+INT_MAX (#3143)
pygame/pygame pull request #3151
Opened 2022-04-24 09:53 UTC by jhilmer

`draw_circle_filled` calls `drawhorzlineclipbounding` the arguments
was not protected for signed interger overflow - which produced a
write bar when e.g. a circle like:
`pygame.draw.circle(display, (255,255,255), (-1e30,300), 10 )` was
drawn.

This commit limit the `x` corrdinate to `drawhorzlineclipbounding`
so signed interger overflow is avoided.

2022-04-26 12:27 UTC, robertpfeiffer commented
Are you imallet's friend, or did you find this independently? I have a different fix for this, but I did not want to make a PR before I looked at this issue. I think we should merge both in any case, and this one before mine, for the sake of correctness.

2022-04-26 21:10 UTC, jhilmer commented
I just stumbled over this open bug, and thought I could fix it.

2022-05-08 16:47 UTC, illume requested changes
@jhilmer could you please add a unit test for this?

2022-05-28 22:56 UTC, illume commented
Hey hey. Let me know if you want someone else to take over writing the test for this?

2023-03-07 04:28 UTC, illume approved these changes
👍 thanks.

It fixes the issue linked.

2023-03-07 04:28 UTC, merged