Remove old thread compat code
pygame/pygame pull request #3166
Opened 2022-05-05 09:00 UTC by Starbuck5

I noticed while looking into #3083 that some older files had these `WITH_THREAD` `#ifdef`s spread liberally around, cluttering the code up a bit and hurting readability.

I researched this and learned that Python used to be able to be built without threading support, which may have been advantageous when threads were exotic, in the python 2 days. The threads documentation states `Changed in version 3.7: This module used to be optional, it is now always available.`

So the only people potentially impacted by this are users on custom builds of Python 3.6, who also update pygame when new releases come out. I'd be surprised if this described any people. Plus we should drop Python 3.6 support soonTM anyways.

2022-05-05 09:39 UTC, ankith26 approved these changes
LGTM! 🥳 

As discussed on discord, we should wait on this PR till we drop 3.6 support, which we should be doing soon

2022-05-07 15:50 UTC, ankith26 commented
On a re-visit... I wonder how this PR effects @ pmp-p s current WASM port efforts, since I believe threads are not well supported with WASM?

2022-05-08 16:45 UTC, illume requested changes
Seems threadless builds are still possible with patched python versions being used. We don't have a test for this or (static builds) so I expect there's a high chance of it being broken.

2022-05-14 07:08 UTC, Starbuck5 commented
@ankith26 and @illume I have high confidence this will work in exotic environments.

1. `WITH_THREAD` is truly obscure. A search of the python docs, 2.7 or 3.x, yields 0 results for this.
2. All the macros guard is code talking about the GIL. A threadless python should have these functions, even if they do nothing.

2022-12-11 06:53 UTC, Starbuck5 commented
I'm giving up on this.

I think there are simplifications we can make to the code here in the future, but it seems like this PR is never going to be merged, so I'll go ahead and close it.

2022-12-11 06:53 UTC, closed without merging