Add aliases for most common objects
pygame/pygame pull request #3356
Opened 2022-07-30 21:20 UTC by PurityLake

Refers to #3353

Added aliases to `pygame` module:
* Joystick
* Font
* Event
* Channel
* Clock

2022-07-30 22:06 UTC, Starbuck5 reviewed
It can't be implemented *quite* this simply, because pygame is built to be modular, and to be okay with certain modules not being compiled with it.

Rect is required, but font is not.

These should go in the try excepts for their respective modules.

2022-07-31 06:28 UTC, Starbuck5 reviewed
Some of these will take a while to get used to... But it'll be a cool change!

I've just realized that these should probably get tiny unit tests, to prevent this new from behavior from unintentional regressions.

It could be as simple as asserting pygame.joystick.Joystick == pygame.Joystick, but for each one.

Oh shoot, how could I forget! This also will need documentation and type hinting support.

2022-07-31 12:05 UTC, PurityLake commented
I'll hop to that then

2022-08-06 20:31 UTC, Starbuck5 commented
This still needs tests and type hints.

2022-10-11 18:04 UTC, PurityLake commented
I believe that should be it for this PR unless I have overlooked something.

2022-11-03 20:30 UTC, MyreMylar requested changes
Seems fine, except `Joystick` is missing from the typestubs.

2022-11-03 20:30 UTC, MyreMylar commented on buildconfig/stubs/pygame/__init__.pyi
> +from .time import Clock as Clock
`Joystick` is missing here.

2022-11-28 18:12 UTC, PurityLake commented on buildconfig/stubs/pygame/__init__.pyi
> +from .time import Clock as Clock
That should be fixed now

2022-12-16 16:41 UTC, MyreMylar approved these changes
LGTM 👍

2023-01-11 04:51 UTC, Starbuck5 reviewed
The `versionchanged` labels should point to 2.1.4 now

2023-01-21 20:36 UTC, PurityLake commented
@Starbuck5 I have made that change to the docs

2023-01-29 11:51 UTC, zoldalma999 commented on buildconfig/stubs/pygame/__init__.pyi
> +from .event import Event as Event
As mentioned in the comment at the top of the file, this is an autogenerated file. Please edit `buildconfig/stubs/gen_stubs.py` instead

2023-01-29 11:51 UTC, zoldalma999 commented on src_py/__init__.py
> +    from pygame.mixer import Channel
`Sound` is missing from here. It needs a test, stubs, and mention in the docs as well (unless it is intentional?).

2023-01-29 11:51 UTC, zoldalma999 commented on src_py/__init__.py
> +    from pygame.event import Event
If the event module is not available, the Event class won't exist. Other modules where the import fails, they define a dummy function (see Cursor for example).

2023-02-16 10:12 UTC, closed without merging