fix CPython was built with clang instead of gcc
pygame/pygame pull request #3381
Opened 2022-08-07 16:10 UTC by pmp-p

as clang does not support unused-but-set-variable

2022-08-09 07:00 UTC, ankith26 commented on setup.py
> +        if sysconfig.get_config_var("MAINCC") != "clang":
I'm not sure how robust this check is...

I had added the `sys.platform not in ("darwin", "win32")` check above just to block this arg being set on clang and MSVC respectively (this flag should only be set on gcc) but this is not a robust check either

The best solution to this that I can find involves more distutils hacks (https://stackoverflow.com/a/1671060) but it should give the accurate compiler name that is being used to compile the code

2022-08-20 09:37 UTC, illume requested changes
As Ankith says, the check should be for "is gcc". 

Sounds like this bug should block 2.1.3 release? (maybe the dev release too?)

2022-08-20 11:27 UTC, illume approved these changes
On second thoughts, I think this check improves things. It also doesn't break things, because msvc is mostly on windows.

It does need to be fixed better... but if there's not a better patch I'll merge this in for 2.1.3.dev6.

2022-08-26 17:45 UTC, MyreMylar approved these changes
This seems reasonable without a good gcc check.

2022-08-28 10:31 UTC, merged