mouse.get_pos(), mouse.get_rel() optimizations
pygame/pygame pull request #3424
Opened 2022-08-22 20:43 UTC by itzpr3d4t0r

## Info
Analogue to #3401, this one implements the same optimization but for `mouse.get_pos()` and `mouse.get_rel()`, bringing a 30-40% improvement overall.
## Performance
Here are performance results and some quick graphs:

**OLD**
```
mean: 11.233, stdev: 0.549
mean: 9.143, stdev: 0.276
------
mean: 10.354, stdev: 0.218
mean: 8.479, stdev: 0.227
```
![myplot](https://user-images.githubusercontent.com/103119829/186014787-c77a2780-b22b-4d00-87fa-fb0a7cd2fdcb.png)
___

**NEW**
```
mean: 8.893, stdev: 0.581
mean: 7.033, stdev: 0.376
------
mean: 7.941, stdev: 0.231
mean: 6.13, stdev: 0.228
```

![myplot](https://user-images.githubusercontent.com/103119829/186014872-5e76daf6-f05e-40cc-bbd7-a18fc41eda6e.png)

### Code

```Python
from statistics import pstdev, fmean
from timeit import repeat

import pygame as pg
from pygame import mouse

from plotting import create_plot

def adjust(x: float) -> float:
    # adjust to milliseconds and round
    return round(x * 1000, 3)

win = pg.display.set_mode((500, 500))

GLOB = {"pg": pg, "mouse": mouse}

REPEATS = 200
NUM = 100000

data = repeat("pg.mouse.get_pos()", globals=GLOB, number=NUM, repeat=REPEATS)
data_1 = repeat("mouse.get_pos()", globals=GLOB, number=NUM, repeat=REPEATS)
data2 = repeat("pg.mouse.get_rel()", globals=GLOB, number=NUM, repeat=REPEATS)
data2_1 = repeat("mouse.get_rel()", globals=GLOB, number=NUM, repeat=REPEATS)

print(f"mean: {adjust(fmean(data))}, stdev: {adjust(pstdev(data))}")
print(f"mean: {adjust(fmean(data_1))}, stdev: {adjust(pstdev(data_1))}")
print("------")
print(f"mean: {adjust(fmean(data2))}, stdev: {adjust(pstdev(data2))}")
print(f"mean: {adjust(fmean(data2_1))}, stdev: {adjust(pstdev(data2_1))}")
```

2022-08-26 04:13 UTC, ankith26 reviewed
Since you are having to make use of `pg_tuple_from_values_int` in 2 PRs... should it be centralised somehow?

IG we will loose the lil inlining speedup if we try to put this in `base.c` as a slot function (which is not that much of a big deal, IG)

2022-08-26 07:06 UTC, itzpr3d4t0r commented
I will test that and let you know, if impact is too big there's no reason to do that

2022-08-27 01:01 UTC, Starbuck5 commented
> try to put this in base.c as a slot function

Or put it in a header file somewhere so it can be globally included?

2022-11-06 20:33 UTC, MyreMylar requested changes
This will need to be updated to use the inline function from #3530 in whatever state that gets merged.

Setting this to 'Request changes' to clean up my PR review list and for clarity.

2022-11-06 21:16 UTC, itzpr3d4t0r commented
> This will need to be updated to use the inline function from #3530 in whatever state that gets merged.
> 
> Setting this to 'Request changes' to clean up my PR review list and for clarity.

Yeah sure just waiting for the merge!

2022-11-08 17:29 UTC, itzpr3d4t0r commented
Ran the last test and apparently performance holds up as expected
```
mean: 8.458, stdev: 0.551
mean: 6.68, stdev: 0.174
------
mean: 7.38, stdev: 0.217
mean: 5.769, stdev: 0.229
```

2022-11-09 06:57 UTC, Starbuck5 approved these changes
Cool!

2022-11-09 06:57 UTC, merged