added boilerplate.py
pygame/pygame pull request #3441
Opened 2022-09-11 05:52 UTC by DatDerpyDude81

Credit to @Starbuck5 for the idea.

2022-09-11 14:34 UTC, illume commented
Against, because we have a full folder of examples showing this isn't the only or good way of doing things.

2022-09-11 14:37 UTC, novialriptide requested changes
```python
if __name__ == "__main__":
    main()
```

You should put this at the bottom and move everything in the while loop into a `main()` function as shown here: https://github.com/pygame/pygame/blob/main/examples/sound.py

2022-09-11 14:37 UTC, novialriptide commented on examples/boilerplate.py
> +# get pygame events
Comments should be on the same indent level as the while loop

2022-09-11 14:37 UTC, novialriptide commented on examples/boilerplate.py
> +import pygame
You should be importing `pygame` as `pg` here to keep consistency with the other examples.

2022-09-12 06:54 UTC, Starbuck5 commented
Issue link: https://github.com/pygame/pygame/issues/3406

Thanks for making a PR.

This isn't exactly what I had in mind. I've seen in other libraries documentation "quickstart" sections that just get people what they need to get started, and that inspired me to think about the bare minimum people need to get started with pygame. One thing that is non obvious is how to set up a game loop. The challenge is how to incorporate this information into the documentation so it's consistent and easily discoverable by new users.

In my opinion, merely putting into `examples/` won't be helpful, because newbies (and the vast majority of pygame users) wouldn't think to look for it there.

2022-09-13 17:53 UTC, DatDerpyDude81 commented
I guess we could mention it in the README, 

> Issue link: #3406
> 
> Thanks for making a PR.
> 
> This isn't exactly what I had in mind. I've seen in other libraries documentation "quickstart" sections that just get people what they need to get started, and that inspired me to think about the bare minimum people need to get started with pygame. One thing that is non obvious is how to set up a game loop. The challenge is how to incorporate this information into the documentation so it's consistent and easily discoverable by new users.
> 
> In my opinion, merely putting into `examples/` won't be helpful, because newbies (and the vast majority of pygame users) wouldn't think to look for it there.

I guess we could the file in the README, or we could put this in the pygame docs website

2022-10-09 07:45 UTC, novialriptide requested changes

2022-10-31 19:36 UTC, MyreMylar commented
What about adding a short 'Getting Started.rst' file under https://github.com/pygame/pygame/tree/main/docs somewhere that is then directly linked to from the main readme on github, and maybe included in the docs website as well?

.rst files work pretty well when linked to from github and can include code chunks. Could have the canonical basic 'open an empty window that won't crash' game loop in it - with a little explanation of each line and why it is needed. I'm actually surprised this doesn't exist somewhere already. Maybe it does and we just need to link it up better from the main readme?

2023-01-29 18:01 UTC, closed without merging