added the handle_event and listerning_events
pygame/pygame pull request #3480
Opened 2022-10-06 02:03 UTC by python-ast-person

2022-10-06 05:18 UTC, novialriptide requested changes
I fail to understand what this PR is actually doing, but I left some reviews. I tested this on my local machine and it fails tests.

2022-10-06 05:18 UTC, novialriptide commented on src_py/sprite.py
> +from pygame.rect   import Rect
Please remove the extra spaces.

2022-10-06 05:18 UTC, novialriptide commented on src_py/sprite.py
> +        acknoleged untill you call Sprite.update_listening_events()
There are a couple of spelling mistakes here. Please fix.

2022-10-06 05:19 UTC, novialriptide commented on src_py/sprite.py
> +            if isinstant(event,EventType):
This isn't a valid function.

2022-10-08 06:46 UTC, novialriptide requested changes

2022-10-08 06:46 UTC, novialriptide commented on src_py/sprite.py
> +            #The previous line only interates over old event types
Btw, the comments should have a space between the hastag and the actual message content

2022-10-31 19:28 UTC, MyreMylar commented
Sorry, but I think it is a very bad idea for us to change the interface of a long-lived python class that we have been encouraging others to subclass from for years, in fact it is specifically built to be sub-classed. 

Why? Because what this will do is cause a method name clash with anyone who has sub-classed Sprite with a function called `handle_event()` that doesn't have the exact same parameters as you have used.

The way to do this with our existing implementations would be yet another new subclass of sprite (like `DirtySprite`). Though I'm not sure it is a great idea for us to just keep adding new sprite subclasses with different features either, I think we arguably already have so many sprite groups that it is confusing.

I think it is fine fore people to handle events for sprites in this way (I do it in a similar way myself) but a tutorial might be the easiest way forward with this idea.

2022-10-31 19:28 UTC, closed without merging