Suggested improvement to font_init
pygame/pygame pull request #3489
Opened 2022-10-09 23:49 UTC by PurityLake

Refers to #3394 

This is a suggested solution to the Font class. It simply makes the font name and size arguments options with default values of "freesansbold.ttf" and 12 respectively.

This is being marked as a draft so it can be discussed.

2022-10-11 13:22 UTC, ankith26 commented on src_c/font.c
> +    PyArg_ParseTuple(args, "|Oi", &obj, &fontsize);
The `return -1;` part is still needed for if `PyArg_ParseTuple` errors

2022-10-11 15:30 UTC, ankith26 commented
Hmm, while we are at the topic of updates to this function signature, how about adding kwargs support in here as well? (as comments in the linked issue suggest as well)

To do that you must use [`PyArg_ParseTupleAndKeywords`](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTupleAndKeywords) instead of `PyArg_ParseTuple`

2022-10-11 17:00 UTC, PurityLake commented
Also updated the Font docs

2022-10-12 03:16 UTC, ankith26 reviewed
Since this is new API, this PR is being put off to 2.1.4, so that more people can get to reviewing it and providing more inputs.

Also as new API, a few updates to the unit tests to test for this is also needed

2022-10-12 03:16 UTC, ankith26 commented on docs/reST/ref/font.rst
> +   a font size of 32 is used.
The docs say the default size is 32, but 12 is implemented in the code

2022-10-16 12:03 UTC, MyreMylar requested changes
All seems fine to me, though I'd like a mini debate on a good name for a keyword argument that represents a python file like object. 

Which is why I'm leaving this on request changes.

2022-10-16 12:36 UTC, PurityLake commented on src_c/doc/font_doc.h
> +#define DOC_PYGAMEFONTFONT "Font(file=None, size=12) -> Font\nFont(filename, size) -> Font\nFont(pathlib.Path, size) -> Font\nFont(object, size) -> Font\ncreate a new Font object from a file"
Hmmm, yes file is wrong. I just checked the docs and I realised I misread it as file, not filename. Unless we want to support being passed a file-like object I'd be happy to change it but maybe that's too much of a change? But we also support pathlib.Path so maybe a different name like "filepath" might be better? It suggests we can pass it as a string or Path object

2022-10-16 13:11 UTC, MyreMylar commented on src_c/doc/font_doc.h
> +#define DOC_PYGAMEFONTFONT "Font(file=None, size=12) -> Font\nFont(filename, size) -> Font\nFont(pathlib.Path, size) -> Font\nFont(object, size) -> Font\ncreate a new Font object from a file"
Underneath in the C code it already does accept a python file like object as well as a file path via SDL RWops. 

I'm just trying to come up with a single name for the keyword argument that encapsulates all these potential inputs for the first parameter. In the past it didn't matter as we were exclusively passing by value so the first parameter could be named differently in the docs depending on the input, but once you turn it into a python keyword you need to use the same keyword when passing in a file path (in string, or Path object format) or a file object.

Does that make sense?

I think I'm currently preferring `source` as a universal parameter name, but `file_path` has the benefit of being by far the most frequently used type of input for the first parameter.

2022-10-16 13:38 UTC, PurityLake commented on src_c/doc/font_doc.h
> +#define DOC_PYGAMEFONTFONT "Font(file=None, size=12) -> Font\nFont(filename, size) -> Font\nFont(pathlib.Path, size) -> Font\nFont(object, size) -> Font\ncreate a new Font object from a file"
I realise my "new suggestion" was the exact same as I had it lol

I'm thinking source or resource. Either one I'd be happy with.

2022-12-24 23:57 UTC, PurityLake commented on src_c/doc/font_doc.h
> +#define DOC_PYGAMEFONTFONT "Font(file=None, size=12) -> Font\nFont(filename, size) -> Font\nFont(pathlib.Path, size) -> Font\nFont(object, size) -> Font\ncreate a new Font object from a file"
I have made that change now

2022-12-25 20:13 UTC, PurityLake commented
No idea why this isn't passing, in any of the instances, the tests go fine for me on Ubuntu 22.04

2023-02-09 14:48 UTC, PurityLake commented
Passes now thankfully

2023-02-13 18:27 UTC, illume approved these changes
👍 thanks

2023-02-13 18:28 UTC, merged