draw mask: Added unit tests for test_arc and test_angle
pygame/pygame pull request #3602
Opened 2022-12-01 06:07 UTC by yujyuj

Added unit test for 3 functions:

1. `test_arc()` in test/draw_test.py
2. `test_convert()` in test/surface_test.py
3. `test_angel()` in test/mask_test.py

2022-12-01 06:39 UTC, novialriptide commented
Why not add more commits to the already existing PR?
https://github.com/pygame/pygame/pull/3570

2023-01-29 18:21 UTC, MyreMylar requested changes
These tests currently don't pass the test runners, or even work locally.

2023-01-29 18:21 UTC, MyreMylar commented on test/surface_test.py
> +            self.assertNotEqual(surface.get_size(), size)
This check does not work, it is failing in the test runners.

Converting a surface does not change the pixel size of it. I'm also a little unsure why you are starting with a display surface. The most frequent purpose of `convert()` is to change a regular surface from one that it is unlike the display surface to one that is much closer to it for faster blitting. 

I would probably start with a 16 or 8 bit surface and verify that it had been changed to have the same depth as the display in a call to convert with no arguments. Then try it with a surface argument and see if the new depths match etc.

2023-03-12 13:20 UTC, illume approved these changes
👍 thanks

2023-03-12 13:31 UTC, illume commented
Merged in https://github.com/pygame/pygame/pull/3753

2023-03-12 13:31 UTC, closed without merging