Create VideoTutorials.rst
pygame/pygame pull request #3604
Opened 2022-12-01 06:37 UTC by chrisvo1992

Page with resourceful video tutorials

2022-12-01 06:43 UTC, novialriptide requested changes
I'm not particularly sure about this since most of these videos seem very randomly grabbed from the internet. Maybe we should attach Youtuber's playlist of pyame tutorials instead?

2022-12-01 06:43 UTC, novialriptide commented on docs/reST/tut/VideoTutorials.rst
> +Total Beginners guide to Pygame
Rename to "Total Beginners Guide to Pygame"

2022-12-01 06:43 UTC, novialriptide commented on docs/reST/tut/VideoTutorials.rst
> +https://youtu.be/FfWpgLFMl7w
This video doesn't exist.

2022-12-11 00:43 UTC, Starbuck5 commented on docs/reST/tut/VideoTutorials.rst
> +The purpose of this page is to pr ovide links to the most popular and resourceful videos
"pr ovide" -> "provide"

2022-12-15 08:23 UTC, Starbuck5 commented
This has been stale for a while without reply by OP, so I'm going to go ahead and close this.

2022-12-15 08:23 UTC, closed without merging