Update __init__.py
pygame/pygame pull request #3639
Opened 2022-12-28 12:53 UTC by SmashedFrenzy16

2022-12-28 16:53 UTC, novialriptide commented on src_py/__init__.py
> +        "Pygame v{} (SDL v{}.{}.{}, Python v{}.{}.{})".format(  # pylint: disable=consider-using-f-string
Lowercase p is usually preferred when referring to "pygame" as per PEP8
https://peps.python.org/pep-0008/#package-and-module-names
![image](https://user-images.githubusercontent.com/35881688/209845891-4679c41f-1bb6-4dc6-997a-e13e56a900df.png)

2022-12-28 18:17 UTC, CodeMaster7000 requested changes
Leave a thanks message to those who contribute. You could say something along the lines of "We appreciate you taking the time to contribute."

2022-12-28 18:27 UTC, SmashedFrenzy16 commented
@novialriptide, I have lower cased pygame

2022-12-28 18:28 UTC, SmashedFrenzy16 commented
@CodeMaster7000, wouldn't that make the message too long? After all, it is displayed when you run a pygame project. But I will try and include something relevant to what you are saying.

2022-12-28 18:56 UTC, novialriptide commented
It's also notable to leave meaningful commit messages instead of just "Update filename"

2023-01-01 00:57 UTC, closed without merging

2023-01-01 00:59 UTC, Starbuck5 commented
Closed via: https://github.com/pygame/pygame/pull/3640#issuecomment-1368308737