Update __init__.py
pygame/pygame pull request #3640
Opened 2022-12-28 13:16 UTC by CodeMaster7000

2022-12-28 13:39 UTC, SmashedFrenzy16 commented
This is copying some of the changes that I made in PR #3639

2022-12-28 13:40 UTC, SmashedFrenzy16 commented
So this PR is not necessary

2022-12-28 13:41 UTC, SmashedFrenzy16 commented
At least, for the `__init__.py`, as that is not needed.

2022-12-28 13:44 UTC, CodeMaster7000 commented
@SmashedFrenzy16 The phrasing is different from that in your PR. An additional message is also included.

2022-12-28 13:49 UTC, SmashedFrenzy16 commented
@CodeMaster7000 you could have told me to update my PR instead. Anyways, you could always delete that file.

2022-12-28 13:57 UTC, CodeMaster7000 commented
@SmashedFrenzy16 I honestly think it is fine for now. Once the change has been made, Pygame will most likely close or merge the PRs anyways.

2022-12-28 14:12 UTC, SmashedFrenzy16 commented
@CodeMaster7000 is cannot be fine that you copy other people's pull requests to only get your merged. The best solution would be to delete the `__init__.py` file because you made unecessary extra commits in that change.

2022-12-28 14:21 UTC, SmashedFrenzy16 requested changes
Delete `__init__.py` from this PR as it is not necessary.

2022-12-28 16:36 UTC, novialriptide commented
> Delete `__init__.py` as it is not necessary.

Deleting the file would break pygame

2022-12-28 16:43 UTC, SmashedFrenzy16 commented
No I mean delete it from this PR

2022-12-28 16:52 UTC, novialriptide commented on src_py/__init__.py
> +    print("Hello from the Pygame community! To contribute, visit https://www.pygame.org/contribute.html. We appreciate you taking the time to do so.")
Lowercase p is usually preferred when referring to "pygame" as per PEP8
https://peps.python.org/pep-0008/#package-and-module-names
![image](https://user-images.githubusercontent.com/35881688/209845752-f57791a4-0f41-4fd5-88e1-df4e4e423f96.png)

2022-12-29 07:00 UTC, oddbookworm commented
@SmashedFrenzy16 @CodeMaster7000 the comments of a pull request is not an appropriate place for you two to argue about whose pull request should contain which changes. If you have a disagreement about something, please sort that out in private. Nobody reviewing your PR's wants to sort through your argument to see if there's any important information there. Also, if someone reviews your PR and it's clear changes to the PR are needed, you won't get a merge unless you fix them. Same goes for failing actions (like the lint check, which means you need to run `python setup.py format`)

2022-12-29 08:17 UTC, CodeMaster7000 commented
I understand and I apologise. It might have got a bit out of hand with 2 PRs having overlapping changes.

2022-12-29 08:57 UTC, SmashedFrenzy16 commented
I also understand and apologise.

2023-01-01 00:57 UTC, Starbuck5 commented
Hey @SmashedFrenzy16 and @CodeMaster7000, I believe these changes make the content slightly worse. I talked to some other contributors and I believe we're in agreement about this, so I'm going to close this and #3639 (similar content)

You seem like you want to help out here, which is admirable. If you'd like to tackle an issue (perhaps you can work together on this, you seem to know each other), #3357 could be good. Alternatively, you could try to enhance the docs. I think one promising area would be function names that are written out instead of linked. If some function description references another function it should be possible to click on that and go to the other function, but I don't believe this is the case in all cases.

2023-01-01 00:57 UTC, closed without merging