pygame.transform.blur
pygame/pygame pull request #3698
Opened 2023-02-04 11:43 UTC by yunline

Add `blur()` to transform module.
```python
def blur(
    surface: Surface,
    radius: int,
    dest_surface: Optional[Surface] = None
) -> Surface: ...
```
Inspired by #3659.

![image](https://user-images.githubusercontent.com/31395137/216765287-551537bb-392e-4095-83f1-4c89266db11c.png)

2023-02-04 23:21 UTC, novialriptide commented
Looks like you need to run `python setup.py format` to pass the linting test.

2023-02-05 03:35 UTC, yunline commented on src_c/transform.c
> +box_blur(SDL_Surface *src, SDL_Surface *dst, int radius)
It takes about 100ms to process a image using this algorithm.

Image: 2048x2048 RGBA
CPU: AMD Ryzen7 6800H

2023-02-06 01:25 UTC, novialriptide requested changes

2023-02-06 01:25 UTC, novialriptide commented on src_c/transform.c
> +    else {
Code quality nitpick: Could you remove the else statement and put the return new surface line at the end of the function?

2023-02-06 01:32 UTC, novialriptide requested changes

2023-02-06 01:32 UTC, novialriptide commented on src_c/transform.c
> +        return RAISE(PyExc_ValueError, "Radius less than zero.");
phrasing could be better like "the radius should not be less than zero"

2023-02-06 01:36 UTC, novialriptide commented
Blurring Better Call Saul is giving me weird results here... I'm not sure if this is normal

### Result
![image](https://user-images.githubusercontent.com/35881688/216862204-6a86c26f-e2cd-4b6d-8898-4b008c6d1ba9.png)

### Original Image
![maxresdefault](https://user-images.githubusercontent.com/35881688/216862216-6e7117c5-6d12-4c4a-a353-752961bf9c87.jpg)

2023-02-06 03:52 UTC, novialriptide commented
You can never go wrong with Saul's good looks.

2023-02-06 08:16 UTC, yunline commented
> It takes about 220ms to process an image using this algorithm.

I optimized the algorithm and now it takes 75ms to process one image.

Image: 2048x2048 RGBA
CPU: AMD Ryzen7 6800H

2023-02-06 10:39 UTC, itzpr3d4t0r commented
I think that a blur function should be named depending on the blur algorithm it uses, so gaussian, bokeh etc.

2023-02-06 20:18 UTC, yunline commented
New parameter `repeat_edge_pixels`
![image](https://user-images.githubusercontent.com/31395137/217075438-517493c1-c7f6-4f22-97d0-5fbc75ee3cf0.png)

2023-02-08 02:50 UTC, yunline commented
Gaussian blur √
![image](https://user-images.githubusercontent.com/31395137/217415220-a22b746d-e600-4380-989e-96a4c4585d84.png)

2023-02-12 10:46 UTC, closed without merging